import location from '../src/assets/cover.jpeg';
import guess from '../src/assets/guessing2.png';
import landing from '../src/assets/landing.png';
import todo from '../src/assets/todo.png';
import real from '../src/assets/realestate.png';
import tech from '../src/assets/techcompany.png';

import React from "react";

function Projects() {
  const projects = [
    {
      title: 'Todo List App',
      description:
        'A simple and clean to-do list app built using HTML, CSS, and JavaScript. Users can add, complete, and delete tasks. Responsive and beginner-friendly.',
      link: 'https://ht1pst.github.io/to-do-list/todo.html',
      images: [todo],
    },
    {
      title: 'Guessing Game',
      description:
        'A fun and interactive guessing game built with JavaScript where users try to guess a number or a word randomly generated by the computer. Features include input validation, win/loss feedback, and dynamic UI updates.',
      link: 'https://ht1pst.github.io/guessingGame/guessgame.html',
      images: [guess],
    },
    {
      title: 'Landing Page',
      description:
        'A modern, responsive landing page designed with HTML and CSS Grid/Flexbox. Emphasis on layout, typography, and visuals.',
      link: 'https://ht1pst.github.io/landingpage/landing.html',
      images: [landing],
    },
    {
      title: 'Real Estate Website',
description: 'A modern and responsive real estate website built with React and Tailwind CSS. This project showcases my front-end skills in creating clean layouts, responsive design, and smooth user interactions. It features intuitive navigation and dynamic property listings to enhance the user experience.',
link: 'https://realestateclean.netlify.app/',
images: [real],
    },

     {
      title: 'Tech Company Website',
  description: 'A sleek and responsive tech company website built with React and Tailwind CSS. This project highlights my ability to design professional-looking layouts, implement responsive sections, and create engaging user experiences with modern front-end tools.',
  link: 'https://techcompanyfinal3.netlify.app/',
  images: [tech],
    },
  ];

  return (
    <section>
      <div
        id="projects"
        className="bg-[#0f0f0f] text-[#f5f5f5] font-sans min-h-screen text-center w-full"
      >
        <div
        ><h1 className='text-5xl font-bold '>Projects</h1>
        </div>
        <main className="max-w-5xl mx-auto py-16 px-4 text-center">
          {projects.map((project, idx) => (
            <div
              key={idx}
              className="bg-white/5 border border-white/10 rounded-xl p-8 mb-12 shadow-lg"
            >
              <h2 className="text-[#2cb67d] text-2xl font-semibold mb-4">
                {project.title}
              </h2>
              <p className="text-lg leading-relaxed mb-6">{project.description}</p>
              <h3 className="text-[#333] font-bold text-lg mb-2">Live Demo:</h3>
              <a
                href={project.link}
                className="text-blue-600 hover:text-blue-800 transition-colors duration-200"
                target="_blank"
                rel="noreferrer"
              >
                View Live Website
              </a>
              <h3 className="text-[#333] font-bold text-lg mt-6 mb-2">Screenshot:</h3>
              <div className="flex flex-wrap justify-center gap-4">
                {project.images.map((img, i) => (
                  <img
                    key={i}
                    src={img}
                    alt={`Screenshot ${i + 1}`}
                    className="w-1/3 min-w-[200px] rounded-lg border border-gray-300 shadow-md"
                  />
                ))}
              </div>
            </div>
          ))}
        </main>
      </div>
    </section>
  );
}

export default Projects;
