import location from '../src/assets/cover.jpeg';
import guess from '../src/assets/guessing2.png';
import landing from '../src/assets/landing.png';
import todo from '../src/assets/todo.png';
import real from '../src/assets/realestate.png';
import tech from '../src/assets/techcompany.png';
import proj1 from "../src/assets/synox.png";
import proj2 from "../src/assets/phunk.png";
import proj3 from "../src/assets/powerflow.png";
import proj4 from "../src/assets/wager.png";
import arrow2 from "../src/assets/arrow.webp";
import React from "react";
import { motion } from "framer-motion";

function Projects() {
  const projects = [
    {
      title: 'Todo List App',
      description:
        'A simple and clean to-do list app built using HTML, CSS, and JavaScript. Users can add, complete, and delete tasks. Responsive and beginner-friendly.',
      link: 'https://ht1pst.github.io/to-do-list/todo.html',
      images: [todo],
    },
    {
      title: 'Guessing Game',
      description:
        'A fun and interactive guessing game built with JavaScript where users try to guess a number or a word randomly generated by the computer. Features include input validation, win/loss feedback, and dynamic UI updates.',
      link: 'https://ht1pst.github.io/guessingGame/guessgame.html',
      images: [guess],
    },
    {
      title: 'Landing Page',
      description:
        'A modern, responsive landing page designed with HTML and CSS Grid/Flexbox. Emphasis on layout, typography, and visuals.',
      link: 'https://ht1pst.github.io/landingpage/landing.html',
      images: [landing],
    },
    {
      title: 'Real Estate Website',
description: 'A modern and responsive real estate website built with React and Tailwind CSS. This project showcases my front-end skills in creating clean layouts, responsive design, and smooth user interactions. It features intuitive navigation and dynamic property listings to enhance the user experience.',
link: 'https://realestateclean.netlify.app/',
images: [real],
    },

     {
      title: 'Tech Company Website',
  description: 'A sleek and responsive tech company website built with React and Tailwind CSS. This project highlights my ability to design professional-looking layouts, implement responsive sections, and create engaging user experiences with modern front-end tools.',
  link: 'https://techcompanyfinal3.netlify.app/',
  images: [tech],
    },
  ];

  return (
    <section className='lg:px-[90px] px-[20px] bg-[#292929] pt-20  '>



      <div
        id="projects"
        className="bg-[#292929] text-[#f5f5f5] font-sans min-h-screen  w-full max-w-350 mx-auto"
      >
        <div
        ><motion.h1 className='text-5xl font-bold text-center'
         initial={{ y: 50, opacity: 0 }}
  whileInView={{ y: 0, opacity: 1 }}
  viewport={{ once: true, amount: 0.3 }}
  transition={{ duration: 0.8, ease: "easeOut" }}
        >Projects</motion.h1>
        </div>

<a href="https://synoxco.netlify.app/">
   <motion.div className="flex flex-col lg:flex-row items-center justify-between rounded border group border-[#616161] lg:py-5 lg:px-6 rounded-2xl mt-10"
    initial={{ y: 50, opacity: 0 }}
  whileInView={{ y: 0, opacity: 1 }}
  viewport={{ once: true, amount: 0.3 }}
  transition={{ duration: 0.8, ease: "easeOut" }}
   >
                <div className="p-[20px]">
<h1 className="text-[1.75rem] font-bold proj-title text-white">Synoxco</h1>

<div className="proj-tools flex flex-wrap  gap-2 mt-3">
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">React + Vite</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Tailwind CSS</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Motion</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Netlify</p>
</div>

<p className="proj-det text-[1.125rem] text-white font-bold max-w-[600px] leading-[23px] mt-10">A sleek fintech landing page created for a digital finance platform. The website focuses on clear communication of financial services, trust-driven design, and responsive UI sections that present the platform’s features in a modern and accessible way.</p>

<a href="#" >
  <button className="flex border w-45 justify-center rounded-full h-13 items-center gap-2 text-[1.1rem] text-white mt-10">View Project <span className="rounded-full bg-white inline-flex items-center justify-center w-7 h-7    "><img src={arrow2} alt="call icon" className="w-[15px]" /></span></button>
    </a>

     <div className='mt-8 block lg:hidden'>
                    <img src={proj1} alt="" className="rounded-xl lg:w-150  rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
                </div>

 <div className='lg:block hidden'>
                    <img src={proj1} alt="" className="rounded-xl lg:w-150  rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
               

            </motion.div>
</a>

<a href="https://phunkk.netlify.app/">
 <motion.div className="flex items-center group justify-between rounded border border-[#616161] lg:py-5 lg:px-6 rounded-2xl mt-10"
  initial={{ y: 50, opacity: 0 }}
  whileInView={{ y: 0, opacity: 1 }}
  viewport={{ once: true, amount: 0.3 }}
  transition={{ duration: 0.8, ease: "easeOut" }}
 >

                <div className="p-[20px]">
<h1 className="text-[1.75rem] font-bold proj-title text-white">Phunkk</h1>

<div className="proj-tools flex flex-wrap gap-2 mt-3">
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">React + Vite</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Tailwind CSS</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Motion</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Netlify</p>
</div>

<p className="proj-det text-[1.125rem] text-white font-bold max-w-[600px] leading-[23px] mt-10">A bold and visually engaging landing page designed for a modern digital brand. The project focuses on strong typography, immersive visuals, and clean layout structures to create an impactful user experience while maintaining performance and responsiveness across devices.</p>

<a href="#" >
  <button className="flex border w-45 justify-center rounded-full h-13 items-center gap-2 text-[1.1rem] text-white mt-10">View Project <span className="rounded-full bg-white inline-flex items-center justify-center w-7 h-7    "><img src={arrow2} alt="call icon" className="w-[15px]" /></span></button>
    </a>

      <div className='mt-8 block lg:hidden'>
                    <img src={proj2} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>

                </div>

 <div className='lg:block hidden'>
                    <img src={proj2} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
             
            </motion.div>
</a>

<a href="https://powerflowco.netlify.app/">
            <motion.div className="flex items-center group justify-between rounded border border-[#616161] lg:py-5 lg:px-6 rounded-2xl mt-10"
             initial={{ y: 50, opacity: 0 }}
  whileInView={{ y: 0, opacity: 1 }}
  viewport={{ once: true, amount: 0.3 }}
  transition={{ duration: 0.8, ease: "easeOut" }}
            >

                <div className="p-[20px]">
<h1 className="text-[1.75rem] font-bold proj-title text-white">Powerflow</h1>

<div className="proj-tools flex flex-wrap gap-2 mt-3">
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">React + Vite</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Tailwind CSS</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Motion</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Netlify</p>
</div>

<p className="proj-det text-[1.125rem] text-white font-bold max-w-[600px] leading-[23px] mt-10">A modern landing page designed for a fitness and gym brand. The site highlights training programs, facilities, and membership options through bold visuals, strong typography, and a responsive layout built to motivate visitors and drive sign-ups.</p>

<a href="#" >
  <button className="flex border w-45 justify-center rounded-full h-13 items-center gap-2 text-[1.1rem] text-white mt-10">View Project <span className="rounded-full bg-white inline-flex items-center justify-center w-7 h-7    "><img src={arrow2} alt="call icon" className="w-[15px]" /></span></button>
    </a>

    <div className='mt-8 block lg:hidden'>
                    <img src={proj3} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
                </div>

  <div className='lg:block hidden'>
                    <img src={proj3} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
               

            </motion.div>
</a>

<a href="https://wagerfunding.netlify.app/">
<motion.div className="flex items-center group justify-between rounded border border-[#616161] lg:py-5 lg:px-6 rounded-2xl mt-10"
 initial={{ y: 50, opacity: 0 }}
  whileInView={{ y: 0, opacity: 1 }}
  viewport={{ once: true, amount: 0.3 }}
  transition={{ duration: 0.8, ease: "easeOut" }}
>

                <div className="p-[20px]">
<h1 className="text-[1.75rem] font-bold proj-title text-white">Wager Funding</h1>

<div className="proj-tools flex flex-wrap gap-2 mt-3">
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">React + Vite</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Tailwind CSS</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Motion</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">Framer Netlify</p>
</div>

<p className="proj-det text-[1.125rem] text-white font-bold max-w-[600px] leading-[23px] mt-10">A modern fintech-style landing page for a sports prediction funding platform that allows users to showcase their skills and earn rewards through performance-based challenges. I designed and developed the responsive interface with a focus on clear information hierarchy, engaging UI sections, and smooth interactions to improve user experience and conversion.</p>

<a href="#" >
  <button className="flex border w-45 justify-center rounded-full h-13 items-center gap-2 text-[1.1rem] text-white mt-10">View Project <span className="rounded-full bg-white inline-flex items-center justify-center w-7 h-7    "><img src={arrow2} alt="call icon" className="w-[15px]" /></span></button>
    </a>

     <div className='mt-8 block lg:hidden'>
                    <img src={proj4} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
                </div>

               <div className='lg:block hidden'>
                    <img src={proj4} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>

            </motion.div>
</a>

<a href="https://ht1pst.github.io/to-do-list/todo.html">
<motion.div className="flex items-center group justify-between rounded border border-[#616161] lg:py-5 lg:px-6 rounded-2xl mt-10"
 initial={{ y: 50, opacity: 0 }}
  whileInView={{ y: 0, opacity: 1 }}
  viewport={{ once: true, amount: 0.3 }}
  transition={{ duration: 0.8, ease: "easeOut" }}
>

                <div className="p-[20px]">
<h1 className="text-[1.75rem] font-bold proj-title text-white">Todo</h1>

<div className="proj-tools flex gap-2 mt-3">
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">HTML</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">CSS</p>
    <p className="border border-white w-auto px-5 h-7 flex justify-center items-center text-white text-[.75rem] font-bold rounded-full">JavaScript</p>
</div>

<p className="proj-det text-[1.125rem] text-white font-bold max-w-[600px] leading-[23px] mt-10">A simple and intuitive task management application that allows users to create, track, and organize daily tasks efficiently. The project focuses on clean UI design, responsive layouts, and dynamic state management to provide a smooth and productive user experience.</p>

<a href="#" >
  <button className="flex border w-45 justify-center rounded-full h-13 items-center gap-2 text-[1.1rem] text-white mt-10">View Project <span className="rounded-full bg-white inline-flex items-center justify-center w-7 h-7    "><img src={arrow2} alt="call icon" className="w-[15px]" /></span></button>
    </a>

     <div className='mt-8 block lg:hidden'>
                    <img src={todo} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
                </div>


<div className='lg:block hidden'>
                    <img src={todo} alt="" className="rounded-xl w-150 rounded-xl object-cover transition-transform duration-300 group-hover:scale-102" />
                </div>
               

            </motion.div>
 </a>


      
      </div>
    </section>
  );
}

export default Projects;
